[build]
  base = "influential-app"
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
