// src/pages/Creators/creatorsData.js
import photo1 from '../../assets/influencer2.svg';
import photo2 from '../../assets/influencer4.svg';
import photo3 from '../../assets/influencer5.svg';
import photo4 from '../../assets/influencer6.svg';
import photo5 from '../../assets/influencer3.svg';
import photo6 from '../../assets/influencer1.svg';

const creators = [
  {
    id: 1,
    photo: photo1,
    handle: 'lucas_crea',
    name: 'Lucas Fernández',
    location: 'Buenos Aires, Arg',
    rating: 5,
    description: 'Creador de contenido especializado en producto y lifestyle. Videos y fotos para redes sociales.',
    contentTypes: ['Video', 'Foto', 'Reel'],
    specialties: ['Producto', 'Lifestyle', 'Gastronomía'],
    priceRange: '$15.000 – $50.000',
    priceMin: 15000,
    priceMax: 50000,
    turnaround: '3-5 días',
    deliveryMin: 3,
    deliveryMax: 5,
    completedProjects: 48,
  },
  {
    id: 2,
    photo: photo2,
    handle: 'cami_visual',
    name: 'Camila Rodríguez',
    location: 'Córdoba, Arg',
    rating: 4,
    description: 'Especialista en UGC para marcas de belleza y skincare. Contenido auténtico y de alta calidad.',
    contentTypes: ['Video', 'Reel', 'Story'],
    specialties: ['Belleza', 'Skincare', 'Moda'],
    priceRange: '$20.000 – $65.000',
    priceMin: 20000,
    priceMax: 65000,
    turnaround: '5-7 días',
    deliveryMin: 5,
    deliveryMax: 7,
    completedProjects: 32,
  },
  {
    id: 3,
    photo: photo3,
    handle: 'mati_produce',
    name: 'Matías González',
    location: 'Rosario, Arg',
    rating: 5,
    description: 'Producción UGC orientada a tecnología y gadgets. Unboxings, reviews y demos de producto.',
    contentTypes: ['Video', 'Unboxing', 'Review'],
    specialties: ['Tech', 'Gaming', 'Electrónica'],
    priceRange: '$25.000 – $80.000',
    priceMin: 25000,
    priceMax: 80000,
    turnaround: '4-6 días',
    deliveryMin: 4,
    deliveryMax: 6,
    completedProjects: 67,
  },
  {
    id: 4,
    photo: photo4,
    handle: 'vale_content',
    name: 'Valentina López',
    location: 'Buenos Aires, Arg',
    rating: 4,
    description: 'Contenido UGC para gastronomía y bebidas. Fotos y videos con estilo editorial.',
    contentTypes: ['Foto', 'Video', 'Reel'],
    specialties: ['Gastronomía', 'Bebidas', 'Lifestyle'],
    priceRange: '$18.000 – $55.000',
    priceMin: 18000,
    priceMax: 55000,
    turnaround: '3-5 días',
    deliveryMin: 3,
    deliveryMax: 5,
    completedProjects: 41,
  },
  {
    id: 5,
    photo: photo5,
    handle: 'nico_ugc',
    name: 'Nicolás Martínez',
    location: 'Mendoza, Arg',
    rating: 5,
    description: 'Creador UGC para marcas de deporte y outdoor. Contenido dinámico y energético.',
    contentTypes: ['Video', 'Reel', 'Story'],
    specialties: ['Deportes', 'Outdoor', 'Fitness'],
    priceRange: '$20.000 – $70.000',
    priceMin: 20000,
    priceMax: 70000,
    turnaround: '5-7 días',
    deliveryMin: 5,
    deliveryMax: 7,
    completedProjects: 53,
  },
  {
    id: 6,
    photo: photo6,
    handle: 'sofi_crea',
    name: 'Sofía Herrera',
    location: 'Buenos Aires, Arg',
    rating: 4,
    description: 'UGC para moda y accesorios. Lookbooks, try-ons y contenido editorial para redes.',
    contentTypes: ['Foto', 'Video', 'Lookbook'],
    specialties: ['Moda', 'Accesorios', 'Lifestyle'],
    priceRange: '$22.000 – $60.000',
    priceMin: 22000,
    priceMax: 60000,
    turnaround: '4-6 días',
    deliveryMin: 4,
    deliveryMax: 6,
    completedProjects: 29,
  },
];

export default creators;
